### ISSUE TITLE
wes - Project 1 

### ISSUE THREAD

**Issue by wesareed** [ga-dc/wdi9-project1-gallery#2]
https://github.com/wesareed/flashcards/tree/gh-pages

wireframe and userStories

**Comment by tylercrosse** [comment]
Your wireframe looks great!

I add a few comments on your bronze user stories. But overall these look good :+1: 

```
1. Want user to be able to learn greek through the use of flashcards 
// This is kind of vague, user stories ideally are actionable
```

```
2. Want user to have the ability to “flip” through flashcards using keyboard arrows or previous/next buttons. 
3. Want user to have the ability to input their answer when shown a vocabulary word 
```

// This is a cool and doable feature, but I would suggest starting with having the user mark them as right or wrong instead of having the program check.
// Taking user input can be a headache as soon as you start to worry about 'fuzzy results' like case sensitivity, spelling, etc.

```
4. Want user to know if they are correct or incorrect
5. Want user to have the ability to recycle through incorrect answers until the user get’s the answer correct. 
```
